export const FRUITS = [
  'apple',
  'apricot',
  'banana',
  'blackberry',
  'blueberry',
  'cantaloupe',
  'cherry',
  'clementine',
  'cranberry',
  'date',
  'dragon fruit',
  'durian',
  'fig',
  'gooseberry',
  'grape',
  'grapefruit',
  'guava',
  'honeydew melon',
  'jackfruit',
  'kiwi',
  'kumquat',
  'lemon',
  'lime',
  'longan',
  'lychee',
  'mango',
  'mangosteen',
  'nectarine',
  'orange',
  'papaya',
  'passion fruit',
  'peach',
  'pear',
  'persimmon',
  'pineapple',
  'plum',
  'pomegranate',
  'pomelo',
  'quince',
  'raspberry',
  'starfruit',
  'strawberry',
  'tangerine',
  'watermelon',
].map((ingredient) => ({key: ingredient, category: 'fruit'}));

export const LEAFIES = [
  'arugula',
  'basil',
  'bok choy',
  'chard',
  'cilantro',
  'collard greens',
  'dandelion greens',
  'endive',
  'escarole',
  'kale',
  'lettuce',
  'mizuna',
  'mustard greens',
  'napa cabbage',
  'parsley',
  'radicchio',
  'romaine',
  'spinach',
  'swiss chard',
  'watercress',
].map((ingredient) => ({key: ingredient, category: 'leafy'}));

export const ROOTS = [
  'beet',
  'black radish',
  'burdock root',
  'carrot',
  'celeriac',
  'daikon',
  'fennel',
  'garlic',
  'ginger',
  'horseradish',
  'jicama',
  'kohlrabi',
  'leek',
  'onion',
  'parsnip',
  'potato',
  'radish',
  'rutabaga',
  'shallot',
  'sweet potato',
  'taro',
  'turnip',
  'wasabi',
  'yam',
].map((ingredient) => ({key: ingredient, category: 'root'}));

export const VEGETABLES = [
  'artichoke',
  'asparagus',
  'bell pepper',
  'bitter melon',
  'broccoli',
  'broccolini',
  'brussels sprouts',
  'cabbage',
  'cauliflower',
  'celery',
  'chayote',
  'corn',
  'cucumber',
  'eggplant',
  'fennel',
  'jicama',
  'okra',
  'peas',
  'pumpkin',
  'radish',
  'rhubarb',
  'snap pea',
  'snow pea',
  'squash',
  'tomato',
  'zucchini',
].map((ingredient) => ({key: ingredient, category: 'vegetable'}));

export const BEANS = [
  'adzuki bean',
  'black bean',
  'black-eyed pea',
  'broad bean',
  'butter bean',
  'cannellini bean',
  'chickpea',
  'cranberry bean',
  'edamame',
  'fava bean',
  'flageolet bean',
  'garbanzo bean',
  'green bean',
  'kidney bean',
  'lentil',
  'lima bean',
  'mung bean',
  'navy bean',
  'pinto bean',
  'red bean',
  'soybean',
  'split pea',
  'white bean',
  'yardlong bean',
].map((ingredient) => ({key: ingredient, category: 'bean'}));
