export const NUTRIENTS: Record<string, readonly string[]> = {
  A: [
    'apricot',
    'bell pepper',
    'broccoli',
    'butternut squash',
    'cantaloupe',
    'carrot',
    'collard greens',
    'dandelion greens',
    'kale',
    'mango',
    'mustard greens',
    'pumpkin',
    'spinach',
    'sweet potato',
  ],
  B1: [
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'macadamia nut',
    'mung bean',
    'oat',
    'peanut',
    'pinto bean',
    'pistachio nut',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'sesame seed',
    'soybean',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
  B2: [
    'almond',
    'champignon',
    'edamame',
    'oat',
    'portobello',
    'shiitake',
    'soybean',
    'spinach',
    'sunflower seed',
    'white bean',
  ],
  B3: [
    'black bean',
    'black-eyed pea',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'red bean',
    'scarlet runner bean',
    'soybean',
    'white bean',
    'champignon',
    'portobello',
    'oat',
    'peanut',
    'sunflower seed',
  ],
  B5: [
    'avocado',
    'black bean',
    'black-eyed pea',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'red bean',
    'scarlet runner bean',
    'soybean',
    'white bean',
    'champignon',
    'portobello',
    'oat',
    'peanut',
    'sunflower seed',
  ],
  B6: [
    'avocado',
    'banana',
    'black lentil',
    'brown lentil',
    'green lentil',
    'oat',
    'pistachio nut',
    'potato',
    'red lentil',
    'sunflower seed',
    'yellow lentil',
  ],
  B7: [
    'almond',
    'champignon',
    'peanut',
    'portobello',
    'shiitake',
    'soybean',
    'sunflower seed',
    'sweet potato',
  ],
  B9: [
    'asparagus',
    'avocado',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'broccoli',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'green lentil',
    'kidney bean',
    'mung bean',
    'pinto bean',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'soybean',
    'spinach',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
  C: [
    'broccoli',
    'brussels sprouts',
    'guava',
    'kale',
    'kiwi',
    'lemon',
    'orange',
    'papaya',
    'bell pepper',
    'spinach',
    'strawberry',
  ],
  E: [
    'almond',
    'avocado',
    'brazil nut',
    'hazelnut',
    'peanut',
    'pine nut',
    'spinach',
    'sunflower seed',
  ],
  K: [
    'arugula',
    'broccoli',
    'brussels sprouts',
    'cabbage',
    'chard',
    'collard greens',
    'kale',
    'lettuce',
    'little gem lettuce',
    'mustard greens',
    'oak leaf lettuce',
    'red leaf lettuce',
    'romaine',
    'spinach',
  ],
  calcium: [
    'almond',
    'broccoli',
    'chia seed',
    'collard greens',
    'kale',
    'sesame seed',
    'spinach',
    'watercress',
    'bok choy',
  ],
  fiber: [
    'almond',
    'avocado',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chia seed',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'mung bean',
    'oat',
    'pear',
    'pinto bean',
    'plum',
    'raspberry',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'soybean',
    'sweet potato',
    'white bean',
    'yellow lentil',
  ],
  iron: [
    'almond',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'green lentil',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'pumpkin seed',
    'quinoa',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'sesame seed',
    'soybean',
    'spinach',
    'white bean',
    'yellow lentil',
  ],
  magnesium: [
    'almond',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'cashew nut',
    'chia seed',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'pumpkin seed',
    'quinoa',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'soybean',
    'spinach',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
  potassium: [
    'avocado',
    'banana',
    'beet',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'broccoli',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'green lentil',
    'kidney bean',
    'kiwi',
    'mung bean',
    'pinto bean',
    'potato',
    'pumpkin',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'soybean',
    'spinach',
    'sweet potato',
    'white bean',
    'yellow lentil',
  ],
  zinc: [
    'almond',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'cashew nut',
    'chia seed',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'pumpkin seed',
    'quinoa',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'sesame seed',
    'soybean',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
};
