export const FRUITS: readonly string[] = [
  'apple',
  'apricot',
  'asian pear',
  'banana',
  'bilberry',
  'blackberry',
  'blackcurrant',
  'blood grapefruit',
  'blood orange',
  'blueberry',
  'boysenberry',
  'calamansi',
  'cantaloupe',
  'cape gooseberry',
  'caper',
  'cherimoya',
  'cherry',
  'clementine',
  'cloudberry',
  'coconut',
  'cranberry',
  'date',
  'dragon fruit',
  'durian',
  'fig',
  'finger lime',
  'goji berry',
  'gooseberry',
  'grape',
  'grapefruit',
  'grenadilla',
  'guava',
  'honeydew melon',
  'jackfruit',
  'kiwi',
  'kumquat',
  'lemon',
  'lime',
  'lingonberry',
  'longan',
  'lychee',
  'mandarin',
  'mango',
  'mangosteen',
  'nectarine',
  'orange',
  'papaya',
  'passion fruit',
  'peach',
  'pear',
  'persimmon',
  'piel de sapo',
  'pineapple',
  'plum',
  'pomegranate',
  'pomelo',
  'prickly pear',
  'quince',
  'rambutan',
  'raspberry',
  'redcurrant',
  'sea buckthorn',
  'starfruit',
  'strawberry',
  'watermelon',
  'yuzu',
];

export const LEAFIES: readonly string[] = [
  'arugula',
  'basil',
  'bok choy',
  'cabbage',
  'chard',
  'choy sum',
  'cilantro',
  'collard greens',
  'dandelion greens',
  'dill',
  'endive',
  'frisee',
  'holy basil',
  'iceberg lettuce',
  'kale',
  'lemon balm',
  'lemongrass',
  'lettuce',
  'little gem lettuce',
  'mache',
  'mint',
  'mizuna',
  'mustard greens',
  'napa cabbage',
  'oak leaf lettuce',
  'oregano',
  'parsley',
  'pea sprouts',
  'radicchio',
  'red cabbage',
  'red leaf lettuce',
  'romaine',
  'rosemary',
  'sage',
  'savoy cabbage',
  'shiso',
  'sorrel',
  'spinach',
  'sprouts',
  'tarragon',
  'thai basil',
  'thyme',
  'water spinach',
  'watercress',
];

export const ROOTS: readonly string[] = [
  'bamboo shoots',
  'beet',
  'black radish',
  'black salsify',
  'carrot',
  'celeriac',
  'chives',
  'daikon',
  'fennel',
  'garlic',
  'ginger',
  'horseradish',
  'jerusalem artichoke',
  'jicama',
  'kohlrabi',
  'leek',
  'manioc',
  'onion',
  'parsley root',
  'parsnip',
  'potato',
  'radish',
  'red onion',
  'rutabaga',
  'scallion',
  'shallot',
  'sweet potato',
  'taro',
  'turnip',
  'wasabi',
  'white onion',
  'yam',
  'yellow beet',
];

export const VEGETABLES: readonly string[] = [
  'artichoke',
  'asparagus',
  'avocado',
  'bell pepper',
  'bitter melon',
  'broccoli',
  'broccolini',
  'brussels sprouts',
  'butternut squash',
  'cauliflower',
  'celery',
  'chayote',
  'cherry tomato',
  'chili pepper',
  'corn',
  'cucumber',
  'eggplant',
  'hokkaido pumpkin',
  'jalapeno',
  'nori',
  'okra',
  'olive',
  'plantain',
  'pointed pepper',
  'pumpkin',
  'rhubarb',
  'spaghetti squash',
  'tomatillo',
  'tomato',
  'wakame',
  'wax gourd',
  'zucchini',
];

export const MUSHROOMS: readonly string[] = [
  'black trumpet mushroom',
  'champignon',
  'chanterelle',
  'enoki',
  'hedgehog mushroom',
  'king oyster mushroom',
  'matsutake',
  'morel',
  'oyster mushroom',
  'porcini',
  'portobello',
  'shiitake',
  'shimeji',
  'wild mushroom',
  'wood ear mushroom',
  'yellowfoot mushroom',
];

export const BEANS: readonly string[] = [
  'black bean',
  'black lentil',
  'black-eyed pea',
  'brown lentil',
  'butter bean',
  'cannellini bean',
  'chickpea',
  'cranberry bean',
  'edamame',
  'fava bean',
  'flageolet bean',
  'green bean',
  'green lentil',
  'kidney bean',
  'mung bean',
  'pea',
  'pinto bean',
  'red bean',
  'red lentil',
  'scarlet runner bean',
  'snow pea',
  'sugar snap pea',
  'soybean',
  'white bean',
  'yardlong bean',
  'yellow lentil',
];

export const GRAINS: readonly string[] = [
  'almond',
  'amaranth',
  'barley',
  'brazil nut',
  'buckwheat',
  'bulgur',
  'cashew nut',
  'chestnut',
  'chia seed',
  'couscous',
  'farro',
  'flaxseed',
  'hazelnut',
  'hemp seed',
  'kamut',
  'macadamia nut',
  'millet',
  'oat',
  'peanut',
  'pecan nut',
  'pine nut',
  'pistachio nut',
  'poppy seed',
  'pumpkin seed',
  'quinoa',
  'rice',
  'rye',
  'safflower seed',
  'sesame seed',
  'sorghum',
  'spelt',
  'sunflower seed',
  'teff',
  'triticale',
  'walnut',
  'wheat',
  'wild rice',
];

export const ALL_VEGGIES: readonly string[] = [
  ...FRUITS,
  ...VEGETABLES,
  ...LEAFIES,
  ...ROOTS,
  ...BEANS,
  ...GRAINS,
  ...MUSHROOMS,
];

export const CITRUSES: readonly string[] = [
  'blood grapefruit',
  'blood orange',
  'calamansi',
  'clementine',
  'finger lime',
  'grapefruit',
  'kumquat',
  'lemon',
  'lime',
  'mandarin',
  'orange',
  'pomelo',
  'yuzu',
];

export const RED_VEGGIES: readonly string[] = [
  'apple',
  'beet',
  'bell pepper',
  'blood grapefruit',
  'blood orange',
  'cherry tomato',
  'cherry',
  'chili pepper',
  'cranberry',
  'goji berry',
  'lingonberry',
  'pointed pepper',
  'pomegranate',
  'radish',
  'raspberry',
  'red bean',
  'red cabbage',
  'red onion',
  'redcurrant',
  'strawberry',
  'tomato',
  'watermelon',
];

export const NUTS: readonly string[] = [
  'almond',
  'brazil nut',
  'cashew nut',
  'chestnut',
  'coconut',
  'hazelnut',
  'macadamia nut',
  'peanut',
  'pecan nut',
  'pine nut',
  'pistachio nut',
  'walnut',
];

export const BOTANICAL_BERRIES: readonly string[] = [
  'avocado',
  'banana',
  'bell pepper',
  'bilberry',
  'blackcurrant',
  'blood grapefruit',
  'blood orange',
  'blueberry',
  'cantaloupe',
  'cape gooseberry',
  'cherry tomato',
  'chili pepper',
  'clementine',
  'cranberry',
  'cucumber',
  'dragon fruit',
  'eggplant',
  'goji berry',
  'grape',
  'grapefruit',
  'guava',
  'honeydew melon',
  'kiwi',
  'kumquat',
  'lemon',
  'lime',
  'mandarin',
  'orange',
  'papaya',
  'passion fruit',
  'piel de sapo',
  'plantain',
  'pointed pepper',
  'pomelo',
  'pumpkin',
  'redcurrant',
  'tomatillo',
  'tomato',
  'watermelon',
  'yuzu',
  'zucchini',
];

export const ONIONS: readonly string[] = [
  'chives',
  'garlic',
  'leek',
  'onion',
  'red onion',
  'scallion',
  'shallot',
  'white onion',
];

export const NUTRIENTS: Record<string, readonly string[]> = {
  A: [
    'apricot',
    'bell pepper',
    'broccoli',
    'butternut squash',
    'cantaloupe',
    'carrot',
    'chard',
    'chili pepper',
    'collard greens',
    'dandelion greens',
    'kale',
    'mango',
    'mustard greens',
    'pumpkin',
    'spinach',
    'sweet potato',
  ],
  B1: [
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'macadamia nut',
    'mung bean',
    'oat',
    'peanut',
    'pinto bean',
    'pistachio nut',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'sesame seed',
    'soybean',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
  B2: [
    'almond',
    'champignon',
    'edamame',
    'oat',
    'portobello',
    'shiitake',
    'soybean',
    'sunflower seed',
    'white bean',
  ],
  B3: [
    'black bean',
    'black-eyed pea',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'red bean',
    'scarlet runner bean',
    'soybean',
    'white bean',
    'champignon',
    'portobello',
    'oat',
    'peanut',
    'sunflower seed',
  ],
  B5: [
    'avocado',
    'black bean',
    'black-eyed pea',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'red bean',
    'scarlet runner bean',
    'soybean',
    'white bean',
    'champignon',
    'portobello',
    'oat',
    'peanut',
    'sunflower seed',
  ],
  B6: [
    'avocado',
    'banana',
    'black lentil',
    'brown lentil',
    'green lentil',
    'oat',
    'pistachio nut',
    'potato',
    'red lentil',
    'sunflower seed',
    'yellow lentil',
  ],
  B7: ['almond', 'champignon', 'peanut', 'portobello', 'shiitake', 'soybean', 'sunflower seed'],
  B9: [
    'asparagus',
    'avocado',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'broccoli',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'green lentil',
    'kidney bean',
    'mung bean',
    'pinto bean',
    'red bean',
    'red lentil',
    'romaine',
    'scarlet runner bean',
    'soybean',
    'spinach',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
  C: [
    'bell pepper',
    'blood orange',
    'broccoli',
    'brussels sprouts',
    'clementine',
    'guava',
    'kale',
    'kiwi',
    'lemon',
    'orange',
    'papaya',
    'pomelo',
    'spinach',
    'strawberry',
  ],
  E: [
    'almond',
    'avocado',
    'brazil nut',
    'hazelnut',
    'peanut',
    'pine nut',
    'spinach',
    'sunflower seed',
  ],
  K: [
    'arugula',
    'broccoli',
    'brussels sprouts',
    'cabbage',
    'chard',
    'collard greens',
    'kale',
    'lettuce',
    'little gem lettuce',
    'mustard greens',
    'oak leaf lettuce',
    'red leaf lettuce',
    'romaine',
    'spinach',
  ],
  calcium: [
    'almond',
    'amaranth',
    'black bean',
    'bok choy',
    'brazil nut',
    'broccoli',
    'chia seed',
    'chickpea',
    'collard greens',
    'kale',
    'mustard greens',
    'sesame seed',
    'teff',
    'watercress',
    'white bean',
  ],
  fiber: [
    'almond',
    'avocado',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chia seed',
    'chickpea',
    'cranberry bean',
    'date',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'mung bean',
    'oat',
    'pear',
    'pinto bean',
    'plum',
    'raspberry',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'soybean',
    'sweet potato',
    'white bean',
    'yellow lentil',
  ],
  iron: [
    'almond',
    'amaranth',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'cashew nut',
    'chia seed',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'green lentil',
    'kamut',
    'kidney bean',
    'oat',
    'pinto bean',
    'pumpkin seed',
    'quinoa',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'sesame seed',
    'soybean',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
  magnesium: [
    'almond',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'cashew nut',
    'chia seed',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'pumpkin seed',
    'quinoa',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'soybean',
    'spinach',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
  potassium: [
    'avocado',
    'banana',
    'beet',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'broccoli',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'green lentil',
    'kidney bean',
    'kiwi',
    'mung bean',
    'pinto bean',
    'potato',
    'pumpkin',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'soybean',
    'spinach',
    'sweet potato',
    'white bean',
    'yellow lentil',
  ],
  zinc: [
    'almond',
    'black bean',
    'black lentil',
    'black-eyed pea',
    'brown lentil',
    'butter bean',
    'cannellini bean',
    'cashew nut',
    'chia seed',
    'chickpea',
    'cranberry bean',
    'edamame',
    'fava bean',
    'flageolet bean',
    'flaxseed',
    'green lentil',
    'kidney bean',
    'mung bean',
    'oat',
    'pinto bean',
    'pumpkin seed',
    'quinoa',
    'red bean',
    'red lentil',
    'scarlet runner bean',
    'sesame seed',
    'soybean',
    'sunflower seed',
    'white bean',
    'yellow lentil',
  ],
};
